version: '3.7'

services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: [ "--config=/etc/collector-config.yaml" ]
    volumes:
      - ./collector-config.yaml:/etc/collector-config.yaml
    ports:
      - "1888:1888"
      - "8888:8888"
      - "8889:8889"
      - "13133:13133"
      - "4317:4317"
      - "55679:55679"

  input-service:
    image: brunobevilaquaa/otel-input-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGET_SERVICE=input
    container_name: input-service
    depends_on:
      - jaeger
      - zipkin
      - otel-collector
    ports:
      - "8080:8080"
    environment:
      - ORCHESTRATION_SERVICE_URL=http://orchestration-service:8081
      - COLLECTOR_URL=otel-collector:4317

  orchestration-service:
    image: brunobevilaquaa/otel-orchestration-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGET_SERVICE=orchestration
    container_name: orchestration-service
    depends_on:
      - jaeger
      - zipkin
      - otel-collector
    environment:
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - COLLECTOR_URL=otel-collector:4317